# routes.yml


route2:
    path:     /catch
    defaults: { _controller: 'DomCrawlerPageParser' }

#default_fallback:
#    path:     /{domain}
#    defaults: { _controller: 'MyController::fooAction' }